[package]
name = "maze-generation"
version = "0.1.0"
authors = ["Logan Saso <logan@imgur.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.7.0"
